spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movieTicketBookingdb?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Welcome123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        hbm2ddl:
          auto: update